
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bill;

import Helper.DBHelper;
import Main.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;






/**
 *
 * @author Manh
 */
public class DoimatkhauNV extends javax.swing.JPanel {
 
    /**
     * Creates new form Khachhang
     */
    
    ResultSet rs;
    PreparedStatement ps;
    DBHelper db = new DBHelper();
    Connection con = db.getCon();
    boolean flag1 = false, flag2 = false, flag3 = false;
    public DoimatkhauNV(String name) {
        initComponents();
        lbName.setText(name);
        lbName.setVisible(false);
          btnOK.setEnabled(false);
       
    
    
       
    }
    
   
   



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbConfirmPass = new javax.swing.JLabel();
        lbPassCu = new javax.swing.JLabel();
        lbPassNew = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbmaukhau4 = new javax.swing.JLabel();
        lbmaukhau5 = new javax.swing.JLabel();
        lbmaukhau6 = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtPassCu = new javax.swing.JPasswordField();
        txtPassNew = new javax.swing.JPasswordField();
        lbName = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(128, 128, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 860, 70));

        lbConfirmPass.setBackground(new java.awt.Color(153, 153, 153));
        lbConfirmPass.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbConfirmPass.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 230, 30));

        lbPassCu.setBackground(new java.awt.Color(153, 153, 153));
        lbPassCu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbPassCu.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbPassCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 220, 30));

        lbPassNew.setBackground(new java.awt.Color(153, 153, 153));
        lbPassNew.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbPassNew.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(lbPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 230, 30));

        btnOK.setText("Đồng ý");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 30));

        jButton2.setText("Làm mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 30));

        lbmaukhau4.setBackground(new java.awt.Color(153, 153, 153));
        lbmaukhau4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbmaukhau4.setForeground(new java.awt.Color(153, 153, 153));
        lbmaukhau4.setText("Nhập Lại Mật Khẩu   :");
        jPanel1.add(lbmaukhau4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, 30));

        lbmaukhau5.setBackground(new java.awt.Color(153, 153, 153));
        lbmaukhau5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbmaukhau5.setForeground(new java.awt.Color(153, 153, 153));
        lbmaukhau5.setText("Mật Khẩu Cũ             :");
        jPanel1.add(lbmaukhau5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 30));

        lbmaukhau6.setBackground(new java.awt.Color(153, 153, 153));
        lbmaukhau6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbmaukhau6.setForeground(new java.awt.Color(153, 153, 153));
        lbmaukhau6.setText("Mật Khẩu Mới           :");
        jPanel1.add(lbmaukhau6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, 30));

        txtConfirmPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtConfirmPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtConfirmPassCaretUpdate(evt);
            }
        });
        jPanel1.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 230, 30));

        txtPassCu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtPassCu.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCuCaretUpdate(evt);
            }
        });
        jPanel1.add(txtPassCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 230, 30));

        txtPassNew.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtPassNew.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassNewCaretUpdate(evt);
            }
        });
        txtPassNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassNewActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 230, 40));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        lbName.setText("Trống");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbName)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbName)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (flag1 == true && flag2 == true && flag3 == true) {
            try {
                ps = con.prepareStatement("Update Employee set Password=? where NameEmp=?");
                ps.setString(1, txtConfirmPass.getText());
                ps.setString(2, lbName.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công.");
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Lỗi 101:: Không thể kết nối đến máy chủ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thất bại!");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtPassCu.setText("");
        txtPassNew.setText("");
        txtConfirmPass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPassNewCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassNewCaretUpdate
        // TODO add your handling code here:
        if (txtPassNew.getText().trim().equals("")) {
            lbPassNew.setText(" ");
            btnOK.setEnabled(false);
        } else if (txtPassNew.getText().equals(txtPassCu.getText())) {
            lbPassNew.setText("Mật khẩu mới phải khác mật khẩu cũ.");
            lbPassNew.setForeground(Color.red);
            btnOK.setEnabled(false);
        } else {
            char x;
            for (int i = 0; i < txtPassNew.getText().length(); i++) {
                x = txtPassNew.getText().charAt(i);
                if (x == ' ') {
                    lbPassNew.setText("Mật khẩu không thể chứa khoảng trắng.");
                    lbPassNew.setForeground(Color.red);
                    flag2 = false;
                    btnOK.setEnabled(false);
                    return;
                }
            }
            while (true) {
                if (txtPassNew.getText().length() < 6 || txtPassNew.getText().length() > 18) {
                    lbPassNew.setText("Độ dài mật khẩu trong khoảng 6-18 kí tự.");
                    lbPassNew.setForeground(Color.red);
                    flag2 = false;
                    btnOK.setEnabled(false);
                    return;
                } else {
                    lbPassNew.setText("Mật khẩu hợp lệ.");
                    lbPassNew.setForeground(Color.blue);
                    flag2 = true;
                    btnOK.setEnabled(false);
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtPassNewCaretUpdate

    private void txtPassNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassNewActionPerformed

    private void txtConfirmPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtConfirmPassCaretUpdate
      if (txtConfirmPass.getText().trim().equals("")) {
            lbConfirmPass.setText(" ");
            btnOK.setEnabled(false);
        } else {
            while (true) {
                if (!txtConfirmPass.getText().equals(txtPassNew.getText())) {
                    lbConfirmPass.setText("Nhập lại mật khẩu phải giống mật khẩu.");
                    lbConfirmPass.setForeground(Color.red);
                    flag3 = false;
                    btnOK.setEnabled(false);
                    return;
                } else {
                    lbConfirmPass.setText("Hợp lệ.");
                    lbConfirmPass.setForeground(Color.blue);
                    flag3 = true;
                    btnOK.setEnabled(true);
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtConfirmPassCaretUpdate

    private void txtPassCuCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCuCaretUpdate
         if (txtPassCu.getText().trim().equals("")) {
            lbPassCu.setText(" ");
            btnOK.setEnabled(false);
        } else {
            try {
                ps = con.prepareStatement("Select * from Employee where NameEmp=? and Password=? COLLATE SQL_Latin1_General_CP1_CS_AS");
                ps.setString(1, lbName.getText());
                ps.setString(2, txtPassCu.getText());
                rs = ps.executeQuery();
                while (true) {
                    if (!rs.next()) {
                        lbPassCu.setText("Sai mật khẩu.");
                        lbPassCu.setForeground(Color.red);
                        flag1 = false;
                        btnOK.setEnabled(false);
                        return;
                    } else {
                        lbPassCu.setText("Đúng mật khẩu.");
                        lbPassCu.setForeground(Color.blue);
                        flag1 = true;
                        btnOK.setEnabled(false);
                        break;
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Lỗi 101:: Không thể kết nối đến máy chủ");
            }
        }
    }//GEN-LAST:event_txtPassCuCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbConfirmPass;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassCu;
    private javax.swing.JLabel lbPassNew;
    private javax.swing.JLabel lbmaukhau4;
    private javax.swing.JLabel lbmaukhau5;
    private javax.swing.JLabel lbmaukhau6;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPasswordField txtPassCu;
    private javax.swing.JPasswordField txtPassNew;
    // End of variables declaration//GEN-END:variables
}
